# Generated by Django 5.2.6 on 2025-12-11 22:00

import uuid
import wedding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('mendhi', 'Mendhi'), ('vidhi', 'Vidhi'), ('wedding', 'Wedding'), ('reception', 'Reception')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Emoji or symbol for the event', max_length=10)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('dress_code', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rsvp_code', models.CharField(default=wedding.models.generate_rsvp_code, help_text='Unique 8-character code for private RSVP access', max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('party_name', models.CharField(blank=True, help_text="Family or group name (e.g., 'The Smith Family')", max_length=200)),
                ('max_guests', models.PositiveIntegerField(default=1, help_text='Maximum number of guests in this party (including primary guest)')),
                ('invited_mendhi', models.BooleanField(default=False)),
                ('invited_vidhi', models.BooleanField(default=False)),
                ('invited_wedding', models.BooleanField(default=False)),
                ('invited_reception', models.BooleanField(default=False)),
                ('rsvp_mendhi', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending')], default='pending', max_length=20)),
                ('rsvp_vidhi', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending')], default='pending', max_length=20)),
                ('rsvp_wedding', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending')], default='pending', max_length=20)),
                ('rsvp_reception', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending')], default='pending', max_length=20)),
                ('guests_mendhi', models.PositiveIntegerField(default=0)),
                ('guests_vidhi', models.PositiveIntegerField(default=0)),
                ('guests_wedding', models.PositiveIntegerField(default=0)),
                ('guests_reception', models.PositiveIntegerField(default=0)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('message', models.TextField(blank=True, help_text='Message from the guest')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this guest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rsvp_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('has_responded', models.BooleanField(default=False)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('guests', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('attending_mendhi', models.BooleanField(default=False)),
                ('attending_vidhi', models.BooleanField(default=False)),
                ('attending_wedding', models.BooleanField(default=False)),
                ('attending_reception', models.BooleanField(default=False)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RSVP (Legacy)',
                'verbose_name_plural': 'RSVPs (Legacy)',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner1_name', models.CharField(default='Sarah', max_length=100)),
                ('partner2_name', models.CharField(default='Michael', max_length=100)),
                ('wedding_date', models.DateField()),
                ('location', models.CharField(default='Mumbai, India', max_length=200)),
                ('hashtag', models.CharField(default='#SarahAndMichaelForever', max_length=100)),
                ('welcome_title', models.CharField(default='Welcome to Our Wedding', max_length=200)),
                ('welcome_message', models.TextField()),
            ],
            options={
                'verbose_name': 'Wedding Info',
                'verbose_name_plural': 'Wedding Info',
            },
        ),
    ]
