# Generated by Django 5.2.6 on 2025-12-12 22:49

from django.db import migrations
import json
import os


def create_guests(apps, schema_editor):
    Guest = apps.get_model('wedding', 'Guest')
    
    # Check if guests already exist
    if Guest.objects.exists():
        print("Guests already exist, skipping import")
        return
    
    # Path to fixture file
    fixture_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'fixtures', 'guests.json')
    
    if os.path.exists(fixture_path):
        with open(fixture_path, 'r') as f:
            guests_data = json.load(f)
        
        for guest in guests_data:
            fields = guest['fields']
            Guest.objects.create(**fields)
        
        print(f"Created {len(guests_data)} guests")
    else:
        # Fallback: create a few test guests
        test_guests = [
            {'name': 'Test Family 1', 'email': 'test1@email.com', 'phone': '1234567890', 'party_name': 'Test Party 1', 'max_guests': 4, 'rsvp_code': 'TESTCODE1', 'invited_mendhi': True, 'invited_vidhi': True, 'invited_wedding': True, 'invited_reception': True, 'has_responded': False},
            {'name': 'Test Family 2', 'email': 'test2@email.com', 'phone': '1234567891', 'party_name': 'Test Party 2', 'max_guests': 4, 'rsvp_code': 'TESTCODE2', 'invited_mendhi': True, 'invited_vidhi': True, 'invited_wedding': True, 'invited_reception': True, 'has_responded': False},
            {'name': 'Sharma Family', 'email': 'sharma@email.com', 'phone': '9876543001', 'party_name': 'The Sharma Family', 'max_guests': 5, 'rsvp_code': 'X3X0LT8N', 'invited_mendhi': True, 'invited_vidhi': True, 'invited_wedding': True, 'invited_reception': True, 'has_responded': False},
        ]
        for guest_data in test_guests:
            Guest.objects.create(**guest_data)
        print(f"Created {len(test_guests)} test guests")


def reverse_guests(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_guests, reverse_guests),
    ]
