# Generated by Django 5.2.6 on 2025-12-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('spouse', 'Spouse'), ('other', 'Other')], default='other', max_length=20)),
                ('invited_mendhi', models.BooleanField(default=False)),
                ('invited_vidhi', models.BooleanField(default=False)),
                ('invited_wedding', models.BooleanField(default=False)),
                ('invited_reception', models.BooleanField(default=False)),
                ('rsvp_mendhi', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending')], default='pending', max_length=20)),
                ('rsvp_vidhi', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending')], default='pending', max_length=20)),
                ('rsvp_wedding', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending')], default='pending', max_length=20)),
                ('rsvp_reception', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending')], default='pending', max_length=20)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='wedding.guest')),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
